ambassador:
  - host: scraper.scotth.uk
    name: scraper-mapping
    prefix: /
ambassador_enabled: true
enableEnvVars: true
enabled: true
envVars:
  ENV_1: thing
  ENV_2: thang
image:
  pullPolicy: Always
  pullSecret: gkereg
  repository: eu.gcr.io/hague-hosting/item-scraper
  tag: v0.0.1
liveness:
  enabled: true
  initialDelay: 30s
  periodSeconds: 30s
name: jenkins
readiness:
  enabled: true
  initialDelay: 30s
  periodSeconds: 30s
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
restartPolicy: Always
servicePort: 80
